export const SOME_MUTATION = 'SOME_MUTATION';
export const PROMISE_ADD_ONE='PROMISE_ADD_ONE';
export const PROMISE_ADD_TWO='PROMISE_ADD_TWO';
export const PERMISSION='PERMISSION';
export const PAGENAME='PAGENAME';